-- =====================================================
-- FIBERLAB VR — ESQUEMA DE BASE DE DATOS (re-sincronizado)
-- Supabase / PostgreSQL
-- Refleja el estado real de la base al 2026-08-14.
-- Cambios vs. versión anterior:
--   * resultados: SIN columna tiempo_segundos (eliminada; Unity ya no la envía)
--   * practicas_grupo: SIN created_at ni activo
--   * encuestas_satisfaccion: tabla agregada
--   * get_auth_uid_by_email(): función agregada
--   * encuestas_satisfaccion: políticas RLS corregidas (por-alumno, no 'true')
-- =====================================================

-- =====================================================
-- ENUMS
-- =====================================================

CREATE TYPE estado_aprobacion AS ENUM (
  'pendiente',
  'aprobado',
  'rechazado'
);

-- =====================================================
-- TABLAS
-- =====================================================

CREATE TABLE usuarios (
  usuario_id          INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  nombre              VARCHAR NOT NULL,
  apellido_paterno    VARCHAR NOT NULL,
  apellido_materno    VARCHAR NOT NULL,
  auth_uid            UUID NOT NULL UNIQUE REFERENCES auth.users(id) ON DELETE CASCADE,
  active_session_uuid UUID,   -- control de sesión única por dispositivo
  created_at          TIMESTAMP DEFAULT now()
);

CREATE TABLE profesores (
  profesor_id          INT PRIMARY KEY REFERENCES usuarios(usuario_id) ON DELETE CASCADE,
  matricula_trabajador VARCHAR NOT NULL UNIQUE,
  estado               estado_aprobacion DEFAULT 'pendiente'
);

CREATE TABLE administrador (
  admin_id INT PRIMARY KEY REFERENCES usuarios(usuario_id) ON DELETE CASCADE
);

CREATE TABLE grupos (
  grupo_id      INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  nombre        VARCHAR NOT NULL,
  codigo_acceso VARCHAR NOT NULL UNIQUE,
  ciclo_escolar VARCHAR NOT NULL,
  profesor_id   INT REFERENCES profesores(profesor_id),
  activo        BOOLEAN DEFAULT true
);

CREATE TABLE alumnos (
  alumno_id INT PRIMARY KEY REFERENCES usuarios(usuario_id) ON DELETE CASCADE,
  boleta    VARCHAR NOT NULL UNIQUE,
  grupo_id  INT REFERENCES grupos(grupo_id) ON DELETE SET NULL
);

CREATE TABLE practicas (
  practica_id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  titulo      VARCHAR NOT NULL,
  descripcion TEXT,
  activo      BOOLEAN DEFAULT true
);

CREATE TABLE practicas_grupo (
  asignacion_id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  grupo_id      INT REFERENCES grupos(grupo_id) ON DELETE CASCADE,
  practica_id   INT REFERENCES practicas(practica_id) ON DELETE CASCADE,
  fecha_inicio  TIMESTAMP NOT NULL,
  fecha_fin     TIMESTAMP NOT NULL
);

CREATE TABLE resultados (
  resultado_id    INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  alumno_id       INT NOT NULL REFERENCES alumnos(alumno_id) ON DELETE CASCADE,
  practica_id     INT NOT NULL REFERENCES practicas(practica_id) ON DELETE CASCADE,
  calificacion    NUMERIC,        -- escala 0-100; sin precisión fija para admitir el valor 100
  respuestas_json JSONB,
  created_at      TIMESTAMP DEFAULT now(),
  CONSTRAINT resultados_unq UNIQUE (alumno_id, practica_id)
);

CREATE TABLE encuestas_satisfaccion (
  encuesta_id     INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  alumno_id       INT NOT NULL UNIQUE REFERENCES alumnos(alumno_id) ON DELETE CASCADE,
  respuestas_json JSONB NOT NULL,
  created_at      TIMESTAMP DEFAULT now()
);

-- =====================================================
-- FUNCIONES AUXILIARES (antes de las policies)
-- =====================================================

CREATE OR REPLACE FUNCTION current_usuario_id()
RETURNS int
LANGUAGE sql
STABLE
SECURITY DEFINER  -- bypasea RLS al consultar usuarios, evita recursión infinita
SET search_path = public
AS $$
  SELECT usuario_id
  FROM usuarios
  WHERE auth_uid = auth.uid()
$$;

CREATE OR REPLACE FUNCTION get_auth_uid_by_email(p_email TEXT)
RETURNS UUID
LANGUAGE sql
SECURITY DEFINER
SET search_path = auth, public
AS $$
  SELECT id FROM auth.users WHERE email = p_email LIMIT 1;
$$;

-- =====================================================
-- ACTIVAR ROW LEVEL SECURITY
-- =====================================================

ALTER TABLE usuarios               ENABLE ROW LEVEL SECURITY;
ALTER TABLE profesores             ENABLE ROW LEVEL SECURITY;
ALTER TABLE administrador          ENABLE ROW LEVEL SECURITY;
ALTER TABLE grupos                 ENABLE ROW LEVEL SECURITY;
ALTER TABLE alumnos                ENABLE ROW LEVEL SECURITY;
ALTER TABLE practicas              ENABLE ROW LEVEL SECURITY;
ALTER TABLE practicas_grupo        ENABLE ROW LEVEL SECURITY;
ALTER TABLE resultados             ENABLE ROW LEVEL SECURITY;
ALTER TABLE encuestas_satisfaccion ENABLE ROW LEVEL SECURITY;

-- =====================================================
-- POLÍTICAS RLS — USUARIOS
-- =====================================================

CREATE POLICY "usuarios_select_propietario"
ON usuarios FOR SELECT
USING (auth_uid = auth.uid());

CREATE POLICY "usuarios_insert_propietario"
ON usuarios FOR INSERT
WITH CHECK (auth_uid = auth.uid());

CREATE POLICY "usuario actualiza su propia sesion"
ON usuarios FOR UPDATE
TO authenticated
USING (auth_uid = auth.uid())
WITH CHECK (auth_uid = auth.uid());

CREATE POLICY "profesor_ver_usuarios_de_sus_alumnos"
ON usuarios FOR SELECT
USING (
  usuario_id IN (
    SELECT alumno_id FROM alumnos
    WHERE grupo_id IN (
      SELECT grupo_id FROM grupos
      WHERE profesor_id = current_usuario_id()
    )
  )
);

-- =====================================================
-- POLÍTICAS RLS — PROFESORES
-- =====================================================

CREATE POLICY "profesor_ver_su_registro"
ON profesores FOR SELECT
USING (profesor_id = current_usuario_id());

-- =====================================================
-- POLÍTICAS RLS — GRUPOS
-- =====================================================

CREATE POLICY "grupos_insert_profesor_aprobado"
ON grupos FOR INSERT
WITH CHECK (
  profesor_id = current_usuario_id()
  AND EXISTS (
    SELECT 1 FROM profesores
    WHERE profesor_id = current_usuario_id()
    AND estado = 'aprobado'
  )
);

CREATE POLICY "grupos_update_profesor"
ON grupos FOR UPDATE
USING (profesor_id = current_usuario_id())
WITH CHECK (profesor_id = current_usuario_id());

CREATE POLICY "grupos_delete_profesor"
ON grupos FOR DELETE
USING (profesor_id = current_usuario_id());

CREATE POLICY "alumnos_leer_grupos_activos"
ON grupos FOR SELECT
TO authenticated
USING (activo = true);

-- =====================================================
-- POLÍTICAS RLS — ALUMNOS
-- =====================================================

CREATE POLICY "alumno_ver_su_registro"
ON alumnos FOR SELECT
USING (alumno_id = current_usuario_id());

CREATE POLICY "alumno_actualizar_su_grupo"
ON alumnos FOR UPDATE
TO authenticated
USING (alumno_id = current_usuario_id())
WITH CHECK (alumno_id = current_usuario_id());

CREATE POLICY "profesor_ver_alumnos_de_sus_grupos"
ON alumnos FOR SELECT
USING (
  grupo_id IN (
    SELECT grupo_id FROM grupos
    WHERE profesor_id = current_usuario_id()
  )
);

-- =====================================================
-- POLÍTICAS RLS — PRÁCTICAS
-- =====================================================

CREATE POLICY "ver_practicas_activas"
ON practicas FOR SELECT
USING (activo = true);

-- =====================================================
-- POLÍTICAS RLS — PRÁCTICAS POR GRUPO
-- =====================================================

CREATE POLICY "alumno_ve_practicas_de_su_grupo"
ON practicas_grupo FOR SELECT
TO authenticated
USING (
  grupo_id IN (
    SELECT grupo_id FROM alumnos
    WHERE alumno_id = current_usuario_id()
  )
);

CREATE POLICY "profesor_insert_practicas_grupo"
ON practicas_grupo FOR INSERT
TO authenticated
WITH CHECK (
  grupo_id IN (
    SELECT grupo_id FROM grupos
    WHERE profesor_id = current_usuario_id()
  )
);

-- =====================================================
-- POLÍTICAS RLS — RESULTADOS
-- =====================================================

CREATE POLICY "alumno_ver_resultados"
ON resultados FOR SELECT
USING (alumno_id = current_usuario_id());

CREATE POLICY "alumno_inserta_su_resultado"
ON resultados FOR INSERT
TO authenticated
WITH CHECK (alumno_id = current_usuario_id());

CREATE POLICY "profesor_ver_resultados_grupo"
ON resultados FOR SELECT
USING (
  alumno_id IN (
    SELECT alumno_id FROM alumnos
    WHERE grupo_id IN (
      SELECT grupo_id FROM grupos
      WHERE profesor_id = current_usuario_id()
    )
  )
);

CREATE POLICY "profesor_actualiza_resultados"
ON resultados FOR UPDATE
USING (
  alumno_id IN (
    SELECT alumno_id FROM alumnos
    WHERE grupo_id IN (
      SELECT grupo_id FROM grupos
      WHERE profesor_id = current_usuario_id()
    )
  )
);

-- =====================================================
-- POLÍTICAS RLS — ENCUESTAS DE SATISFACCIÓN (corregidas)
-- Cada alumno solo inserta/ve su propia encuesta.
-- El panel admin lee vía service_role (omite RLS).
-- =====================================================

CREATE POLICY "alumno_inserta_su_encuesta"
ON encuestas_satisfaccion FOR INSERT
TO authenticated
WITH CHECK (alumno_id = current_usuario_id());

CREATE POLICY "alumno_ve_su_encuesta"
ON encuestas_satisfaccion FOR SELECT
TO authenticated
USING (alumno_id = current_usuario_id());